name: test install scripts
on: [push]
jobs:
  install:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: run macos setup script
        run: ./mac/setup.sh
